cargo-features = ["edition2024"]

[workspace]
resolver = "2"
members = [ "lib", "cli" ]

[workspace.dependencies]
horizon-lib = { path = "lib", workspace = true }

serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
anyhow = "1.0.98"
